### PR TITLE
Fix Bug for angles > 90º

### PR DESCRIPTION
**Pull request by david-lorenzo88**
Hello,
There's a small bug that apply only for rotation angles greater than 90 degrees or less than -90º, and generates and incorrect crop coordinates that when sent to the server side, derivates in incorrect cropped images.

The bug is located in getRotatedSizes function of cropper.js:

1. Firstly we need to module the degrees by 180 to limit the angle calculation, as the plugin gives you a 360º based angle.
```javascript
degree = _ref5.degree % 180;
```
2. Lastly, when converting degrees to radians, we need to get the inverted angle when the original angle is greater than 90º.
```javascript
var arc = (degree > 90 ? (180 - degree) : degree) * Math.PI / 180;
```
This is the modified function:
```javascript
/**
 * Get the new sizes of a rectangle after rotated.
 * @param {Object} data - The original sizes.
 * @returns {Object} The result sizes.
 */
function getRotatedSizes(_ref5) {
  var width = _ref5.width,
      height = _ref5.height,
      degree = _ref5.degree % 180;
  
  degree = Math.abs(degree);

  if (degree % 180 === 90) {
    return {
      width: height,
      height: width
    };
  }
  
  var arc = (degree > 90 ? (180 - degree) : degree) * Math.PI / 180;
  var sinArc = Math.sin(arc);
  var cosArc = Math.cos(arc);

  return {
    width: width * cosArc + height * sinArc,
    height: width * sinArc + height * cosArc
  };
}
```

### CODE REVIEW

**Comment by fengyuanchen** [comment]
What are you doing?

**Comment by david-lorenzo88** [comment]
Hello,

I am using your plugin to crop an image in a modal. I am using your crop
example with the php side script. But coordinates sent by cropped.js when
rotation angle is greater than 90° are incorrect . As O explained you in
the pull request.

Best
David

**Comment by fengyuanchen** [comment]
I mean why pull the commits that I had already committed before? 

And [I had already fixed this problem about a month ago](https://github.com/fengyuanchen/cropper/pull/950/commits/91a76392992a6bec19bd9630360a173ee1ecce1f)!

**Comment by david-lorenzo88** [comment]
Ok maybe I did the wrong thing to submit the change.
In the version I downloaded a week ago is not corrected. The version number
of cropper.js is 3.1.3 from 2017-10-21

**Comment by fengyuanchen** [comment]
The problem is fixed but not release yet.

**Comment by david-lorenzo88** [comment]
Ok sorry for the confusion.

**Pull request closed without merging**
