### PR TITLE
Prevent zoom in more than natural width/height of image

### PR DESCRIPTION
**Pull request by ongun-kanat**
Zooming in too much causes problems. I've added a small fix.

### CODE REVIEW

**Comment by fengyuanchen** [comment]
We allow to zoom in more than natural size. Sorry!

**Comment by Donny5300** [comment]
Then why dont add it as a option? Like @ongun-kanat there are more people that could use this, including me

**Comment by amitava82** [comment]
This should be an option.

**Comment by fengyuanchen** [comment]
Why? If you do this, then when you choose an small image as 10 x 10 pixels, you will be hard to see it.

**Pull request closed without merging**
