### PR TITLE
Add support to imgMovable option

### PR DESCRIPTION
**Pull request by gfpacheco**
This was all I could do in my work time because it wasn't a mandatory feature.
But I would appreciate any feedback for me to improve the PR.

### CODE REVIEW

**Comment by fengyuanchen** [comment]
The `movable` option is for image only in v0.10.0. Thank you!

**Comment by RaagaviSridhar** [comment]
After zooming in, i need to move the image before cropping the required portion of the image, setting movable option to true, is also not working. Is there any other property that we need to pair up to make it work.

**Comment by fengyuanchen** [comment]
@RaagaviSridhar You can try to set the `cropBoxMovable` option to `false`.

**Comment by RaagaviSridhar** [comment]
@fengyuanchen even after that I am not able to move the image. I have view mode as 3. Does this problem depends on container and canvas dimensions ? Or view mode 3? Or am I missing any other property.

**Comment by fengyuanchen** [comment]
@RaagaviSridhar There are some limits in `viewMode: 3`, just check the documentation for detail.

**Pull request closed without merging**
