### PR TITLE
fix #666 expose getSourceCanvas and isCropped functionality

### LINKED ISSUE #666: getCroppedCanvas should not fail when not cropping.
If you call `.cropper("clear");` and then call `.cropper('getCroppedCanvas')` you don't get a canvas. Now I understand if I had destroyed the cropper that yes `getCroppedCanvas` should fail. However clear should just clear the cropping feature (I have a button where the user can toggle this on or off). You can achieve a similar issue if you go to the [demo](http://fengyuanchen.github.io/cropper/) site and click the "clear" button and then the "getCroppedCanvas" no image shows up. I really think this should display the entire image in the canvas completely un-cropped.

I previously wrote about the issue in #624 but further testing revealed this more systemic problem.

Example errors when this is happening:

Microsoft

> TypeError: Object doesn't support property or method 'toDataURL'

Firefox on Windows

> TypeError: $modal.find(...).cropper(...).toDataURL is not a function

Safari on Mac

> TypeError: $modal.find('.upload-image').cropper('getCroppedCanvas').toDataURL is not a function. (In '$modal.find('.upload-image').cropper('getCroppedCanvas').toDataURL()', '$modal.find('.upload-image').cropper('getCroppedCanvas').toDataURL' is undefined)

### PR DESCRIPTION
**Pull request by vinnymac**

### CODE REVIEW

**Comment by fengyuanchen** [comment]
I think it is unnecessary to add two more methods here as the `getCroppedCanvas` can return the source canvas directly if not cropped:
```js
...
getCroppedCanvas: function (options) {
  ...

  if (!_this.isBuilt || !SUPPORT_CANVAS) {
    return;
  }

  if (!_this.isCropped) {
    return getSourceCanvas(this.$clone[0], this.image);
  }
  ...
}
...
```

**Comment by vinnymac** [comment]
That was my original proposal [here](https://github.com/fengyuanchen/cropper/issues/666#issuecomment-213480093).

The one you 👍 was the two methods, so I assumed that was the pull request I should make. Anyways, I will change it to be like the original in that case.

**Comment by fengyuanchen** [comment]
Sorry, what I mean is the user can customize it as you say in their project, not to implement it in the Cropper.

**Comment by vinnymac** [comment]
It should be good now :). Let me know if their are issues.

**Comment by fengyuanchen** [comment]
Good work~

**Pull request merged**
