### PR TITLE
Flip image

### PR DESCRIPTION
**Pull request by filipp-qoma**
New feature: flip image by horizontal or vertical or both sides

### CODE REVIEW

**Comment by filipp-qoma** [comment]
I'm sorry if I did mistakes in naming of methods (for example, "flip" instead of "mirror") and mixed "horizontal" and "vertical". Just say me about it and I'll change it ;)

**Comment by fengyuanchen** [comment]
@filipp-qoma I need time to think whether it's necessary to support flip feature. Thank you first!

**Comment by filipp-qoma** [comment]
In my opinion your plugin is best than other crop-plugins. But I need flip feature in my own project. So I decided to improve your plugin for me and for other developers. Maybe someone else like your cropper but has to use the another one with flip function.

**Comment by filipp-qoma** [comment]
Pull request is ready to merge into v.0.9.0

**Comment by fengyuanchen** [comment]
You don't really complete it, you also need to update the `getCroppedCanvas` method.

This feature is not necessary for most people, and in order to keep this plugin simple and lightweight, my suggestion is that keeps this in your own branch.

Maybe we will support it in the future, but not now. I'm very sorry for this. 

Thank you for your work!

**Comment by filipp-qoma** [comment]
`getCroppedCanvas` doesn't need to be updated, because it uses `getSourceCanvas` where flip is implemented. It works. Thank you for your attention.

**Comment by vizo** [comment]
It is sad that this will not be implemented...

@fengyuanchen how do you know "This feature is not necessary for most people"?
I see already 2 issues about this ... I need this also.

**Comment by DS-Matt** [comment]
I see it both ways, it would be a nice feature to add and it doesn't seem like it bloats the codebase.  However the more functionality added the more bloated the app gets... 

I still would vote to include this feature (that makes 4).

**Comment by fengyuanchen** [comment]
I have implemented this feature in v0.11.0. Thank you all!

**Pull request closed without merging**
