### PR TITLE
Add RTL support

### PR DESCRIPTION
**Pull request by MohammadYounes**
This PR adds RTL support by:

1. **CSS**: keeping the container LTR and flipping the rest.
2. **JS**: flipping horizontal directions `west`/`east`.

### CODE REVIEW

**Comment by MohammadYounes** [comment]
@fengyuanchen  Any comments on this!

**Comment by fengyuanchen** [comment]
@MohammadYounes Sorry! I need time to learn RTL as I don't understand how it works.

**Comment by fengyuanchen** [comment]
Maybe only the following line is necessary:
```css
direction: ltr !important; // Ingore global rtl
```

**Comment by MohammadYounes** [comment]
This won't do it! Try it inside an RTL document.

**Comment by MohammadYounes** [comment]
@fengyuanchen You are right, only direction change is required. Having this installed inside an RTL web app, where all styles are automatically RTLed required the JS flipping! 

I submitted a new PR #342

Thanks.

**Pull request closed without merging**
