### PR TITLE
Exif orientation correction should not depend on options

### PR DESCRIPTION
**Pull request by mattjs**

### CODE REVIEW

**Comment by fengyuanchen** [comment]
I don't think so. If you need this case in your project, just keep these code in your own folk. Thanks anyway.

**Comment by mattjs** [comment]
So if I disable rotation and scaling, and then use an image that has Exif
orientation data you don't want to correct the rotation? This seems wrong
can you explain to me you reasoning?

**Comment by fengyuanchen** [comment]
For example, if the users set the `scalable` option to `false`, it means they don't want to scale the image at all.

**Comment by mattjs** [comment]
But at the same time you drop support for properly reading Exif orientation
data.

Let's say I take a horizontal photo on my phone that is properly rotated
using Exif orientation data. When I look at in the browser or on my
computer it looks fine. Then I want to crop the photo, but in this scenario
rotating and scaling are disabled because of bad cross browser support or
for other reasons. When I upload my photo to the cropper it is oriented the
wrong way.

Below is an example photo. If tou try it out I think you may understand the
issue better.

https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Landscape_1.jpg

**Pull request closed without merging**
