### PR TITLE
Added fixedWidth and fixedHeight options. Cropping one image for multiple images and sizes

### PR DESCRIPTION
**Pull request by celilunver**
… and multiple sizes image same time.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [guidelines](https://github.com/fengyuanchen/cropper/blob/master/.github/CONTRIBUTING.md#commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other, Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by fengyuanchen** [comment]
Does this is the same as the `width` and `height` options of the [Cropper.js's `getCroppedCanvas`](https://github.com/fengyuanchen/cropperjs#getcroppedcanvasoptions) method?

**Comment by celilunver** [comment]
I tried but ist not work because when cropping image one aspect. And when i crop for different sizes rounded pixels not equal my width and height values this reason is one aspect ratio

**Comment by fengyuanchen** [comment]
For cropping an image with different aspect ratio, you can change the aspect ratio by the `setAspectRatio` method before do the cropping.

**Comment by fengyuanchen** [comment]
Sorry, thanks for your PR, but I cannot merge this.

**Pull request closed without merging**
