### PR TITLE
New viewMode option: 4 - image should be constrained to the container on rotate, cropBox should be constrained to the image. 

### PR DESCRIPTION
**Pull request by ndtreviv**
I wanted an option whereby if the image was rotated, it would automatically resize so that it fitted within the container (ie: so none of the image would overflow the container when rotated).

For this purpose I've created a new option (with associated test and README.md doc) to do just that named: fitCanvasToContainer.
It works quite well for our purposes.

I have a quandry as towhether or not this should really be a new viewMode...?

### CODE REVIEW

**Comment by ndtreviv** [comment]
PS: When I ran the latests tests before making my changes, two of them were failing. I haven't fixed tests that were already failing.

**Comment by ndtreviv** [comment]
@fengyuanchen I've just simplified this massively. What are your thoughts on whether or not it should be another viewmode instead of an option?

**Comment by fengyuanchen** [comment]
Try this: `$().cropper('clear').cropper('rotate', 90).cropper('crop')`.

**Comment by ndtreviv** [comment]
That seems fine on my tests? Did you have a problem with it? I'm currently in the process of turning it into a new viewmode and adding another constraint: that the cropbox should always be within the bounds of the image, even when the image is rotated. Similar to viewmode:1, but on viewmode:1 the corners overlap when the image is rotated because it's only limited to the canvas, not the image.

**Comment by fengyuanchen** [comment]
I meant this code `$().cropper('clear').cropper('rotate', 90).cropper('crop')` do the same work as your `fitCanvasToContainer ` option.

**Comment by ndtreviv** [comment]
What about: $().cropper('clear').cropper('rotate', 35).cropper('crop')?

Also, doing it that way fires off all the crop events multiple times. Having the option doesn't.

**Comment by ndtreviv** [comment]
$().cropper('clear').cropper('rotate', 35).cropper('crop') doesn't restrain the canvas to the container, unfortunately.

**Comment by fengyuanchen** [comment]
Alright, I think a new option named `rotateMode` will be more reasonable.
- `rotateMode: 0` (default)
- `rotateMode: 1` (fit canvas to container )

**Comment by ndtreviv** [comment]
The problem with this is that rotateMode conflicts with viewMode: 1.

I think it should be a new viewMode along with other stuff. I think I'm going to change it.

**Comment by ndtreviv** [comment]
I've changed this pull request so that it includes all of the new functionality we’ve added.

The new functionality defines where you can and cannot drag the cropBox, which, according to existing convention - ie: viewMode 1 defines that you cannot drag the cropBox outside of the canvas - makes it a new viewMode.

I also believe that the rotate mode functionality should be bundled with the new viewMode because otherwise it conflicts with other aspects of the other viewModes.

**Comment by fengyuanchen** [comment]
I think `viewMode: 4` are not very useful. I'd like to keep the cropper as simple as possible.

**Comment by ndtreviv** [comment]
Ok, but at the moment each viewMode already has it's own rotation behaviour. Also, viewMode 1 constrains the cropbox inside the canvas, but not the image. 

So if you'd rather I change the functionality to two new options, one of which totally overrides the whole point of the other viewmodes, then I can, but surely that's less simple than one new viewMode?

**Pull request closed without merging**
