### PR TITLE
Fixing IE10=< event issues

### PR DESCRIPTION
**Pull request by fizk**
IE10=< will not understand this `e.pageX`, but he will this `e.originalEvent.pageX`

### CODE REVIEW

**Comment by fengyuanchen** [comment]
`e.pageX` and `e.pageY` are supported by jQuery.

**Comment by fizk** [comment]
I can't get this to work in IE, this PR fixed that problem.

Could you maybe guide me to a solution?

**Comment by fengyuanchen** [comment]
What's version of your IE? The Cropper supports IE8/9/10/11.

**Comment by fizk** [comment]
I have tried IE8/9/10/11, it only works in 11.

I used BrowserStack for testing. The bug is that the cropping selection will not resize in IE10 and less

**Comment by fengyuanchen** [comment]
You can try [IETester](http://www.my-debugbar.com/wiki/IETester/HomePage/).

**Comment by fizk** [comment]
BrowserStack is a real Windows OS running a real IE in a virtual machine... so it will provide a real MouseEvent.

I also see that others have had this problem as well https://github.com/fengyuanchen/cropper/issues/377

**Comment by fengyuanchen** [comment]
So, just find a real IE, and test it yourself (your hand exactly), not by machine. #377 is not the same issue as yours.

**Comment by fizk** [comment]
OK here is what I did.

I found a real computer with real IE10.

I ran your demo (http://fengyuanchen.github.io/cropper/). It did not work.

Then I cloned your repo, created an index.html page and added this:

```html
<!doctype html>
<html>
	<head>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
		<link  href="/dist/cropper.css" rel="stylesheet">
		<script src="/dist/cropper.js"></script>
	</head>
	<body>

		<div class="container">
			<img src="/picture.png">
		</div>

		<script type="text/javascript">

			$('.container > img').cropper({
			  aspectRatio: 16 / 9,
			  crop: function(data) {
			    // Output the result data for cropping image.
			  }
			});

		</script>
	</body>
</html>
```

Next I tried it with jQuery v1.9.1, v1.11.3 and v2.1.4. It did not work.

Then I hopped into the debugger to see what was going on.

This is the stack for onDragStart. As you can see, `startX` and `startY` is `undefined`, 'cause `e` has no `pageX` and `pageY`.

before

Next I changed `e.pageX` to `originalEvent.pageX` and `e.pageY` to `originalEvent.pageY` and added a breakpoint on the same line.

Now everything worked. `this` has its `startX` and `startY` values set.
 
after

I don't know why this happens and why `e` does not have it's `pageX`and `pageY` properties set.

I was wondering if IE is using its global `event` object and not the argument passed to the function here:

```js
dragmove: function (event) {
      var options = this.options,
          originalEvent = event.originalEvent,
          touches = originalEvent && originalEvent.touches,
          e = event, //< ---- here
          dragType = this.dragType,
          dragMoveEvent,
          touchesLength;
```

anyways... by using the original event, I can get this to work. I guess I'll just use my fork for my project.

thanks for all your help and replies.

**Comment by pmcalabrese** [comment]
I get the same issue, cannot move the crop handles in IE10.

**Comment by billsliu** [comment]
I test on real IE 9, 10, 11. Original code works on IE9 and IE 11 but not IE 10.
After I change e.pageX to e.originalEvent.pageX;
IE 10 works, I can move crop, but it is broken in ios devices.
e.pageX works on every platform except IE10
e.originalEvent.pageX works on every platform except IOS

The real solution is change 
          e.pageX to e.pageX || e.originalEvent.pageX
          e.pageY to e.pageY || e.originalEvent.pageY
it works on all platform.

**Comment by fizk** [comment]
@billsliu did that pass in the qunit  tests as well?

**Comment by fgodet** [comment]
+1 for this fix! 
So far, the last release version is "0.10.1" and this fix is not part of it. Any idea when will be the next release?
Thx!

**Comment by fizk** [comment]
@fgodet: this PR has been closed by @fengyuanchen, so I guess that this will not go into master...

**Comment by fgodet** [comment]
oh right :/
But still looks like a real issue to me ... I don´t understand why it was closed ...

**Pull request closed without merging**
