### PR TITLE
AMD registration hotfix

### PR DESCRIPTION
**Pull request by filipp-qoma**
Cropper factory has to return jQruery-plugin function

### CODE REVIEW

**Comment by fengyuanchen** [comment]
As a jQuery plugin, it is not necessary to return $.fn.cropper.

**Comment by filipp-qoma** [comment]
Without that line your jquery-plugin cannot be loaded via requirejs. Try it yourself.

**Comment by filipp-qoma** [comment]
A lot of jQuery plugins doesn't have `define` function call, so they can be exported with RequireJS shim. But your plugin has `define` function call, but 'factory' doesn't return any object. So RequireJS returns `undefined`.
Yes, of course, the cropper will be in global jQuery object, but using global object inside RequireJS callbacks is bad practice. Because there can be a lot of different jQuery with different versions in RequireJS project. And because of "map" option of RequireJS it can load different jQuery into different callbacks.
So, you have two ways:
1. remove AMD check and `define` function call and leave only registration as jQuery plugin (so developers can get cropper function via shim and export);
2. add `return $.fn.cropper` at the end of your factory and `define` callback will return cropper function.

**Comment by fengyuanchen** [comment]
Trust me, try this:
```html
<!DOCTYPE html>
<html>
<head>
  <title>Require test</title>
</head>
<body>
  <div class="container">
    <img src="//fengyuanchen.github.io/cropper/img/picture.jpg">
  </div>
  <link rel="stylesheet" href="//fengyuanchen.github.io/cropper/css/cropper.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.1.16/require.min.js"></script>
  <script>
    require.config({
      paths: {
        jquery: '//code.jquery.com/jquery-1.11.2.min',
        cropper: '//fengyuanchen.github.io/cropper/js/cropper.min',
      }
    });

    require(['jquery', 'cropper'], function ($) {
      $('.container > img').cropper();
    });
  </script>
</body>
</html>
```

**Pull request closed without merging**
